# Generated by Django 3.2.4 on 2023-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0002_category_movies_myfavorite_myfavoritemoviesandseries_series_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
