# Generated by Django 3.2.4 on 2023-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Netflix', '0003_auto_20230613_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movieName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='movieName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
